version: "3.8"

services:
  server:
    container_name: server-app
    restart: unless-stopped
    image: server-image
    build:
      context: server
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    networks:
      - shared-network
  client:
    container_name: client-app
    image: client-image
    restart: unless-stopped
    build:
      context: client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - shared-network
networks:
  shared-network: